[package]
name = "fanotify"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", optional = true }
libc = "0.2"
thiserror = "2"
bitflags = "2"

[features]
default = []
aio = ["dep:tokio"]
aio-async-read-write = []
